//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketplaceLocalDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lot()
        {
            this.Marketplace1 = new HashSet<Marketplace1>();
        }
    
        public string Customer { get; set; }
        public string DateCreated { get; set; }
        public string Cost { get; set; }
        public string Description { get; set; }
        public string SiteId { get; set; }
        public string DateStart { get; set; }
        public string SourceLink { get; set; }
        public string Code { get; set; }
        public int Id { get; set; }
        public string DateEnd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marketplace1> Marketplace1 { get; set; }
    }
}
