//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketplaceDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marketplace
    {
        public string Customer { get; set; }
        public string DateCreated { get; set; }
        public string Cost { get; set; }
        public string Description { get; set; }
        public string SiteId { get; set; }
        public string DateFilling { get; set; }
        public string SourceLink { get; set; }
        public string Code { get; set; }
        public int Id { get; set; }
    }
}
