//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketplaceLocalDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarketplacesEntities : DbContext
    {
        public MarketplacesEntities()
            : base("name=MarketplacesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InformationOnMarketplace> InformationOnMarketplace { get; set; }
        public virtual DbSet<Lot> Lot { get; set; }
        public virtual DbSet<Marketplace1> Marketplace1 { get; set; }
        public virtual DbSet<ParseParameter> ParseParameter { get; set; }
    }
}
