//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketplaceLocalDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParseParameter
    {
        public int Id { get; set; }
        public Nullable<double> CostFrom { get; set; }
        public Nullable<double> CostTo { get; set; }
        public Nullable<System.DateTime> PublishDateFrom { get; set; }
        public Nullable<System.DateTime> PublishDateTo { get; set; }
    }
}
